#!/usr/bin/env python3
import click

from src.console_server.console_server import ConsoleServer


@click.command()
def console_server():
    server = ConsoleServer(48)
    server.start()
    server.join()


if __name__ == '__main__':
    console_server()
